### ISSUE TITLE
[Bug] Changes to README or RELEASE_NOTES triggers unwanted checks

### ISSUE THREAD

**Issue by hiimjako** [zaphiro-technologies/github-workflows#78]
### Describe the bug

It is annoying that when an update is made only to the release notes or readme all the checks are relaunched. Just the syntaxcheck and Markdown ones would be enough.
it would be nice to avoid having to wait minutes for build even if only the readme was changed

### Expected Behavior

Only Markdown and syntaxcheck should re-run

### Steps To Reproduce

- Open a PR in a golang repository
- Push a commit with a README or RELEASE_NOTE change
- All checks triggers

### Version

main

**Comment by hiimjako** [comment]
Also, an annoying thing, which I don't know if it can be solved, is that every time you want to merge a Dependabot PRs there is to manually fix the release note because there are always conflicts, I don't know if there is a way to avoid that (Like telling him to always accept the current), so that the checks can restart without human input

**Comment by chicco785** [comment]
If dependabot would allow to create pr as draft, that would solve in combination with blocking the release note generation if not final. Alternative could be generating release note only on merge, but I am not so happy about the idea, because the approval of the check of the log in the release note, for me is part of the review process.

**Comment by chicco785** [comment]
you can see of the merge of the pr https://github.com/zaphiro-technologies/github-workflows/pull/72
would affect a repository here: https://github.com/zaphiro-technologies/architecture/pull/164

I am not saying is the best solution, but it's a progress.
A more definitive solution (for this issue and any other issue related to useless cyclic action on not changed code) is to modify https://github.com/dorny/paths-filter to raise only changes between current and previous commit. This requires anyhow much more time.

So please, unless you have any other idea that preserve quality of the process, review, and merge the pr #72 so that we can at least mitigate the issue.

Thx

**Comment by chicco785** [comment]
The wf now is generating release note only on approval, this may solve the issue with dependabot as well.

**Comment by chicco785** [comment]
for go builds, a similar approach using https://github.com/dorny/paths-filter to trigger build only on the change of go / test data should be followed. the pattern for files, need to support configuration since it may be specific to the project (because for example test data are in different format / locations in different projects).

**Comment by chicco785** [comment]
@zaphiro-technologies/platform with last merged PRs markdown wf and release note wf are triggered only when a pr is approved. This means that before merging you have to wait them to complete.

**Comment by chicco785** [comment]
@hiimjako the generation only on approval of release notes, should solve the dependabot issue

**Comment by chicco785** [comment]
I just tested this approving 3 dependabot PRs on c37 server, for me it's working correctly.
